services:
  # Serviço do banco de dados PostgreSQL
  postgres:
    container_name: postgres-db-banking
    image: postgres:13-alpine
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d finances" ]
      interval: 10s
      timeout: 5s
      retries: 10

  rabbitmq:
    container_name: rabbitmqbanking
    image: rabbitmq:3-management
    ports:
      - "5675:5672"
      - "15675:15672" # Interface de administração
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    networks:
      - app-network

    # Serviço da aplicação Java
  app:
    container_name: wundu-banking
    build: .
    ports:
      - "8088:8081"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      WUNDU_RABBITMQ_HOST: rabbitmqbanking  # <-- muda isso!
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_started
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres-data:

networks:
  app-network:
    external: true