version: '3.8'

services:
  # Serviço do banco de dados PostgreSQL
  postgres:
    container_name: postgres-db-banking
    image: postgres:13-alpine
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: finances
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d finances" ]
      interval: 5s
      timeout: 5s
      retries: 5

    # Serviço da aplicação Java
  app:
    container_name: my-banking
    build: .
    ports:
      - "8082:8081"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    dns:
      - 8.8.8.8
      - 1.1.1.1

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge