server:
  port: 8081  # Porta padrão 8089 para dev

spring:
  datasource:
    url: jdbc:postgresql://interchange.proxy.rlwy.net:32484/railway
    username: postgres
    password: WsdgCporTAgWzRCUQJgJADDRGkRtYEtz
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
    flyway:
      baseline-on-migrate: true
      locations: classpath:db/migration
      enabled: true
    hikari:
      initialization-fail-timeout: 60000

  rabbitmq:
    host: wundu-rabbitmq.railway.internal
    port: 5672
    username: guest
    password: guest

spring-doc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

api:
  key: 123456789SECRETKEY