server:
  port: 8081  # Porta padrão 8089 para dev

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finances
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate.id.new_generator_mappings: false
    flyway:
      baseline-on-migrate: true
      locations: classpath:db/migration
      enabled: true
    hikari:
      initialization-fail-timeout: 60000

spring-doc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

api:
  key: 123456789SECRETKEY