server:
  port: 8081  # Porta padrão 8089 para dev

spring:
  datasource:
    url: jdbc:postgresql://interchange.proxy.rlwy.net:32484/railway
    username: postgres
    password: WsdgCporTAgWzRCUQJgJADDRGkRtYEtz
    driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
        ddl-auto: none
    flyway:
      baseline-on-migrate: true
      locations: classpath:db/migration
      enabled: true
    hikari:
      initialization-fail-timeout: 60000

  rabbitmq:
    host: wundu-rabbitmq.railway.internal  # Domínio interno do RabbitMQ
    port: 5672
    username: wunduuser
    password: wundupass123
    connection-timeout: 30000
    template:
      retry:
        enabled: true
        initial-interval: 1000
        max-attempts: 3
        max-interval: 5000

spring-doc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

api:
  key: 123456789SECRETKEY